# Generated by Django 5.1.5 on 2025-01-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('points_required', models.IntegerField()),
                ('image', models.ImageField(upload_to='badges/')),
            ],
        ),
        migrations.AddField(
            model_name='reward',
            name='badges',
            field=models.ManyToManyField(blank=True, to='accounts.badge'),
        ),
    ]
