# Generated by Django 5.1.5 on 2025-01-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200428_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('found', 'Found Item'), ('lost', 'Lost Item')], default='found', max_length=255),
        ),
    ]
