# Generated by Django 5.1.5 on 2025-01-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_found',
            field=models.BooleanField(default=False),
        ),
    ]
