# Generated by Django 5.1.5 on 2025-01-21 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_is_found'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_found',
        ),
    ]
